server:
  port: 4444
spring:
  application:
    name: HR
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.74:3306/hr?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4GFBgPprPqBTC7gc5NTE
      keysecret: yNrZsSpHNqgw5Qa7iiW1uAa6HGy5iH
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-102