server:
  port: 4444
spring:
  application:
    name: HR
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.74:3306/hr?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.56.74
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        pool:
          max-wait: -1
          #最大阻塞等待时间(负数表示没限制)
          max-idle: 5
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4GFBgPprPqBTC7gc5NTE
      keysecret: yNrZsSpHNqgw5Qa7iiW1uAa6HGy5iH
      bucketname: edu-102
jwt:
  config:
    key: AKAKILLA
    ttl: 10800000